# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 957a4fba337ed5f72d62691bcf64a07ff98df09cb3295bb50f5c22a9a77e6fd12301922eb5e34802de45b7971f7c601f6183d8dd0bca80512b81eb03a251a9fc

test:
  secret_key_base: 4c01f1aa17afd259bff5f1b3156af1f292253c5f0353e6d3a02b57f9a4ca055dc2649eac77a3c8fb4158264a176fe23f0f4314f975451655903a737b8264711b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
